services:
  - type: web
    name: rishabh-villa-lonavala
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
